<template>
  <div
    class="BlockText"
    :class="computedClass"
    v-html="text"
  ></div>
</template>
<script lang="ts">
/**
 * Description of this component
 */
import { defineComponent } from 'vue'

export interface BlockTextObject {
  blockType?: string
  value: string
}

const variants = {
  small: 'text-body-sm -small',
  medium: 'text-body-md -medium',
  large: 'text-body-lg -large'
} as const

export type VariantKey = keyof typeof variants

export default defineComponent({
  name: 'BlockText',
  props: {
    /**
     * Block contents. Supports rich text.
     */
    text: {
      type: String,
      required: false,
      default: undefined
    },
    /**
     * Adjusts text size and vertical spacing. Corresponds with the same variants in `BlockInlineImage`
     */
    variant: {
      type: String as () => VariantKey,
      required: false,
      default: 'large',
      validator: (prop: VariantKey) => Object.keys(variants).includes(prop)
    }
  },
  computed: {
    /**
     * Class string generated by variant selection.
     */
    computedClass(): string {
      return variants[this.variant]
    }
  }
})
</script>
<style lang="scss">
@import '@explorer-1/common/src/scss/components/BlockText';
</style>
