<template>
  <div>
    <MixinFancybox
      :src="theImageData.original"
      :caption="theImageData.caption"
      :credit="theImageData.credit"
      :detail-url="theImageData.detailUrl"
      :gallery-name="`carousel-${blockId}`"
      :title="showTitle ? theImageData.title : null"
      show-thumbnails
    >
      <BaseImagePlaceholder v-if="theImageData" aspect-ratio="16:9" dark-mode>
        <BaseImage
          v-if="theImageData.src"
          :src="theImageData.src.url"
          :srcset="theImageData.srcSet"
          :width="theImageData.src.width"
          :height="theImageData.src.height"
          :alt="theImageData.alt"
          object-fit-class="contain"
          image-class="swiper-lazy"
          loading="lazy"
        />
      </BaseImagePlaceholder>
    </MixinFancybox>
    <div
      v-if="theImageData && hasCaptionArea"
      class="lg:px-0 lg:pt-3 px-4 pt-10"
    >
      <BaseImageCaption class="slide-caption" :data="theImageData" />
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import MixinFancybox from './../MixinFancybox/MixinFancybox.vue'
import BaseImage from './../BaseImage/BaseImage.vue'
import BaseImagePlaceholder from './../BaseImagePlaceholder/BaseImagePlaceholder.vue'
import BaseImageCaption from './../BaseImageCaption/BaseImageCaption.vue'

export default defineComponent({
  name: 'BlockImageCarouselItem',
  components: {
    MixinFancybox,
    BaseImage,
    BaseImagePlaceholder,
    BaseImageCaption,
  },
  props: {
    image: {
      type: Object,
      required: true,
      default: () => ({}),
    },
    // if a caption should even be visible
    displayCaption: {
      type: Boolean,
      default: true,
    },
    // overrides caption provided with image model
    caption: {
      type: String,
      required: false,
    },
    // used to differentiate the fancybox of this carousel from others on the page; generated by Wagtail
    blockId: {
      type: String,
      required: false,
    },
    // if image titles should be displayed in the carousel's fancybox
    showTitle: {
      type: Boolean,
      required: false,
      default: false,
    },
  },
  computed: {
    theCaption(): String | null {
      if (this.caption && this.caption.length > 2 && this.displayCaption) {
        return this.caption
      } else if (
        this.displayCaption &&
        this.image &&
        this.image.caption &&
        this.image.caption.length > 2
      ) {
        return this.image.caption
      }
      return null
    },
    // reform the data object with the computed caption
    theImageData(): object | null {
      if (this.image) {
        return {
          ...this.image,
          caption: this.theCaption,
        }
      }
      return null
    },
    hasCaptionArea(): string | boolean {
      if (this.image) {
        return this.theCaption || this.image.credit || this.image.detailUrl
      }
      return false
    },
  },
})
</script>
<style lang="scss">
@import '@explorer-1/common/src/scss/components/BlockImageCarouselItem';
</style>
