<template>
  <div
    v-if="theImageData"
    class="BlockImageCarouselItem"
  >
    <MixinFancybox
      :src="theImageData.original || theImageData.src?.url"
      :caption="theImageData.caption"
      :credit="theImageData.credit"
      :detail-url="theImageData.detailUrl"
      :gallery-name="`carousel-${blockId}`"
      :title="showTitle ? theImageData.title : undefined"
      show-thumbnails
    >
      <BaseImagePlaceholder
        v-if="theImageData"
        aspect-ratio="16:9"
        dark-mode
      >
        <BaseImage
          v-if="theImageData.src"
          :src="theImageData.src.url"
          :srcset="theImageData.srcSet"
          :width="theImageData.src.width"
          :height="theImageData.src.height"
          :alt="theImageData.alt"
          object-fit-class="contain"
          loading="lazy"
        />
      </BaseImagePlaceholder>
    </MixinFancybox>
    <div
      v-if="theImageData && hasCaptionArea"
      class="caption-area lg:px-0 lg:pt-3 px-4 pt-10"
    >
      <BaseImageCaption
        class="slide-caption"
        :data="theImageData"
      />
    </div>
  </div>
</template>
<script lang="ts">
import { defineComponent, type PropType } from 'vue'
import type { ImageObject } from '../../interfaces'
import MixinFancybox from './../MixinFancybox/MixinFancybox.vue'
import BaseImage from './../BaseImage/BaseImage.vue'
import BaseImagePlaceholder from './../BaseImagePlaceholder/BaseImagePlaceholder.vue'
import BaseImageCaption from './../BaseImageCaption/BaseImageCaption.vue'

export default defineComponent({
  name: 'BlockImageCarouselItem',
  components: {
    MixinFancybox,
    BaseImage,
    BaseImagePlaceholder,
    BaseImageCaption
  },
  props: {
    image: {
      type: Object as PropType<ImageObject>,
      required: true,
      default: () => ({})
    },
    /** If caption should be visible */
    displayCaption: {
      type: Boolean,
      default: true
    },
    /** Overrides caption provided by `{ImageObject}` */
    caption: {
      type: String,
      required: false
    },
    /** 'Fancybox: the block id is used to differentiate the fancybox of the items in a carousel from other carousels on the page. Generated by Wagtail. Usually provided by parent component `BlockImageCarousel`.' */
    blockId: {
      type: String,
      required: false
    },
    /** Fancybox: if the image title should be displayed in the item's fancybox. Usually provided by parent component `BlockImageCarousel`. */
    showTitle: {
      type: Boolean,
      required: false,
      default: false
    }
  },
  computed: {
    theCaption(): string | undefined {
      if (this.caption && this.caption.length > 2 && this.displayCaption) {
        return this.caption
      } else if (
        this.displayCaption &&
        this.image &&
        this.image.caption &&
        this.image.caption.length > 2
      ) {
        return this.image.caption
      }
      return undefined
    },
    // reform the data object with the computed caption
    theImageData(): Partial<ImageObject> | null {
      if (this.image) {
        return {
          ...this.image,
          caption: this.theCaption
        }
      }
      return null
    },
    hasCaptionArea(): string | boolean | undefined {
      if (this.image) {
        return this.theCaption || this.image.credit || this.image.detailUrl
      }
      return false
    }
  }
})
</script>
<style lang="scss">
@import '@explorer-1/common/src/scss/components/BlockImageCarouselItem';
</style>
