version: 2
snapshot:
  widths:
    - 1280
  minHeight: 1024
  percyCSS: ''
  disableShadowDOM: false
  enableJavascript: true
  enableLayout: true
discovery:
  concurrency: 15
storybook:
  # args: {}
  # globals: {}
  # queryParams: {}
  # waitForTimeout: 30000
  # waitForSelector: ''
  # additionalSnapshots: []
  include: [
      'Templates/PageNewsDetail: Hero Carousel',
      'Templates/PageEventDetail: PageEventDetail',
      'Templates/EDU/PageContent: PageContent'
      # 'Foundations/Typography: Text Styles',
      # 'Foundations/Themes: Dynamic Tokens',
      # 'Foundations/Logos/LogoTribrand: Logo Inline SVG',
      # 'Foundations/Grid and Layout: Full Page Example',
      # # TODO: add a story that has all icons in it
      # 'Navigation/*',
      # 'Components/*',
      # 'Mixins/*',
      # 'Templates/*'
    ]
  exclude:
    [
      'Docs',
      'Overview',
      'Navigation/Headers/WWW/NavDesktop: Dropdown',
      'Navigation/Headers/WWW/NavMobile: With Secondary Nav',
      'Navigation/Headers/WWW/NavMobile: With Tertiary Nav',
      'Navigation/Headers/WWW/NavMobile: Dropdown Secondary',
      'Navigation/Headers/EDU/NavMobile',
      'Navigation/Elements',
      'Components/Base/BaseHeading',
      'Components/Base/BaseAudio: BaseAudio',
      'Components/Base/BaseImage: Lazy Loading',
      'Components/Base/BaseImagePlaceholder: With Image',
      'Components/Base/BaseModal: Base Story',
      'Components/Base/BaseModal: Custom Trigger',
      'Components/Base/BaseModal: Nested',
      'Components/Base/BaseSwimlane: Base Story',
      'Components/Base/BaseVideo: Base Story',
      'Components/Blocks/BlockCircleImageCard: Base Story',
      'Components/Blocks/BlockCta: Base Story',
      'Components/Blocks/BlockIframeEmbed: Lazy Load',
      'Components/Blocks/BlockImageCarousel/BlockImageCarouselItem: BlockImageCarouselItem',
      'Components/Blocks/BlockLinkCarousel: Two Items',
      'Components/Blocks/BlockLinkCarousel: Multiple Carousels',
      'Components/Heroes/Small: Video',
      'Snapshot found: Components/Heroes/Small: HeroMedium (compact)',
      'Components/WWW/Homepage/HomepageCarousel: Carousel with shuffled items',
      'Components/WWW/Homepage/HomepageCarousel: Carousel with few slides',
      'Components/WWW/Homepage/HomepageCarousel/HomepageCarouselItem: Single Item',
      'Components/WWW/Homepage/HomepageCarousel/HomepageCarouselItem: With Video',
      'Components/WWW/Homepage/HomepageMissionsCarousel: Item',
      'Components/WWW/MissionDetail/MissionDetailHero: Ecostress',
      'Components/WWW/MissionDetail/MissionDetailHero: Jason 3',
      'Components/WWW/MissionDetail/MissionDetailHero: Oco 2',
      'Components/WWW/MissionDetail/MissionHighlights: Mars 1',
      'Components/WWW/MissionDetail/MissionHighlights: Mars 2',
      'Components/WWW/MissionDetail/MissionHighlights: Moon',
      'Components/WWW/MissionDetail/MissionHighlights: Jupiter',
      'Components/WWW/TopicDetail/MissionCarousel/TopicDetailMissionCarouselItem: Base Story',
      'Components/WWW/TopicDetail/TopicDetailMore: No List',
      'Components/WWW/TopicDetail/TopicDetailMore: No Spotlight',
      'Components/WWW/TopicDetail/TopicDetailMore: Short List',
      'Mixins/MixinCarousel: BaseCarousel'
    ]
