require('@fancyapps/ui')
require('./vendors/_lazysizes.js')
require('./vendors/_swiper.js')
require('./components/_HeroMedia.js')
require('./components/_BlockAccordion.js')
require('./components/_HeaderInternal.js')
