const fs = require('fs')
const path = require('path')

const ARTIFACT_FILE_NAME = 'licensed-fonts-base64.css'
const OUTPUT_FILE_NAME = 'fonts-data.js' // The file preview.ts will import
const SCRIPT_DIR = path.resolve(__dirname)

// Path to the downloaded artifact
const LICENSED_CSS_PATH = path.resolve(SCRIPT_DIR, '..', ARTIFACT_FILE_NAME)
// Path to write the final JS module
const OUTPUT_FILE = path.resolve(SCRIPT_DIR, '..', OUTPUT_FILE_NAME)

let jsModuleContent = `
/** * THIS IS THE SAFE FALLBACK MODULE. 
 * The licensed font artifact was not found by the CI script.
 */
export function injectLicensedFonts() {
    // console.log("Font injector skipped: artifact not found.");
}
`

try {
  // 🛑 CRITICAL CHECK: Does the artifact exist? 🛑
  if (fs.existsSync(LICENSED_CSS_PATH)) {
    const cssContent = fs.readFileSync(LICENSED_CSS_PATH, 'utf8')
    jsModuleContent = `
/** * THIS FILE IS AUTOGENERATED with LICENSED FONT DATA. */
export const licensedFontStyles = \`${cssContent}\`;

export function injectLicensedFonts() {
    if (typeof document !== 'undefined') {
        const styleTag = document.createElement('style');
        styleTag.textContent = licensedFontStyles;
        document.head.appendChild(styleTag);
        console.log('✅ Licensed Fonts injected via JS module.');
    }
}
`
    console.log('✅ Successfully read licensed font data.')
  } else {
    console.log(
      '⚠️ Licensed font artifact NOT found on CI runner. Generating using placeholder module.'
    )
  }

  // Write the resulting JS file (whether it has content or is a placeholder)
  fs.writeFileSync(OUTPUT_FILE, jsModuleContent)
  console.log(`✅ Injection module created at ${OUTPUT_FILE}.`)
} catch (error) {
  console.error('❌ FATAL FAILURE INJECTING FONTS:', error.message)
  process.exit(1)
}
