const fs = require('fs')
const path = require('path')

// --- Configuration & Path Setup (No Changes Needed) ---
const ARTIFACT_FILE_NAME = 'licensed-fonts-base64.css'
const OUTPUT_DATA_FILE_NAME = 'fonts-data.js'
const OUTPUT_FLAG_FILE_NAME = 'font-flag.js'
const SCRIPT_DIR = path.resolve(__dirname)

// Paths are calculated relative to the script's directory (e.g., packages/common-storybook/src/scripts/)
const LICENSED_CSS_PATH = path.resolve(SCRIPT_DIR, '..', ARTIFACT_FILE_NAME)
const OUTPUT_DATA_FILE = path.resolve(SCRIPT_DIR, '..', OUTPUT_DATA_FILE_NAME)
const OUTPUT_FLAG_FILE = path.resolve(SCRIPT_DIR, '..', OUTPUT_FLAG_FILE_NAME)

let isFontDataAvailable = false // Assume false until success

try {
  let jsModuleContent // Variable to hold the content for fonts-data.js

  // 1. ATTEMPT TO READ ARTIFACT AND GENERATE DATA MODULE
  if (fs.existsSync(LICENSED_CSS_PATH)) {
    // --- SUCCESS PATH: Artifact exists ---
    const cssContent = fs.readFileSync(LICENSED_CSS_PATH, 'utf8')

    // Generate the module with actual font data
    jsModuleContent = `
/** * THIS FILE IS AUTOGENERATED with LICENSED FONT DATA. */
export const licensedFontStyles = \`${cssContent}\`;

export function injectLicensedFonts() {
    if (typeof document !== 'undefined') {
        const styleTag = document.createElement('style');
        styleTag.textContent = licensedFontStyles;
        document.head.appendChild(styleTag);
        console.log('✅ Licensed Fonts injected via JS module.');
    }
}
`
    isFontDataAvailable = true
    console.log('✅ Successfully read licensed font data.')
  } else {
    // --- FAILURE/FALLBACK PATH: Artifact is missing ---
    jsModuleContent = `export function injectLicensedFonts() {}`
    isFontDataAvailable = false
    console.log(
      '⚠️ Licensed font artifact NOT found on CI runner. Generating safe placeholder module.'
    )
  }

  // 2. WRITE BOTH OUTPUT FILES

  // Write the Font Data Module
  fs.writeFileSync(OUTPUT_DATA_FILE, jsModuleContent)
  console.log(`✅ Font data module created at ${path.basename(OUTPUT_DATA_FILE)}`)

  // Write the Global Flag Module (CRITICAL STEP for client-side detection)
  const flagContent = `window.__IS_LICENSED_FONT_AVAILABLE__ = ${isFontDataAvailable};`
  fs.writeFileSync(OUTPUT_FLAG_FILE, flagContent)
  console.log(`✅ Global flag module created at ${path.basename(OUTPUT_FLAG_FILE)}`)
} catch (error) {
  console.error('❌ FATAL FAILURE INJECTING FONTS:', error.message)
  process.exit(1)
}
