/**
 * This is necessary to inject licensed fonts in CI/CD for visual regression testing and Storybook rendering
 */

const fs = require('fs')
const path = require('path')

// --- Configuration ---
const ARTIFACT_FOLDER_NAME = 'explorer-1-licensed-fonts'
const ARTIFACT_FILE_NAME = 'licensed-fonts-base64.css'
// Output file that preview.ts will import, place in common-storybook/src/
const OUTPUT_FILE = path.resolve(__dirname, '..')
// artifact is downloaded to common-storybook/src/
const LICENSED_CSS_PATH = path.resolve(__dirname, '..', ARTIFACT_FOLDER_NAME, ARTIFACT_FILE_NAME)

try {
  // 1. Read the raw CSS content
  const cssContent = fs.readFileSync(LICENSED_CSS_PATH, 'utf8')

  // 2. Wrap the CSS content in a Vue/JS setup function
  // This creates a clean, cross-browser JavaScript module.
  const jsModuleContent = `
/** * THIS FILE IS AUTOGENERATED BY inject-fonts.js during CI. 
 * DO NOT EDIT MANUALLY. 
 */
export const licensedFontStyles = \`${cssContent}\`;

export function injectLicensedFonts() {
    if (typeof document !== 'undefined') {
        const styleTag = document.createElement('style');
        styleTag.textContent = licensedFontStyles;
        document.head.appendChild(styleTag);
        console.log('✅ Licensed Fonts injected via JS module.');
    }
}
`

  // 3. Write the resulting JS file to the .storybook folder
  fs.writeFileSync(OUTPUT_FILE, jsModuleContent)
  console.log(`\n✅ Successfully injected CSS into ${path.basename(OUTPUT_FILE)}.`)
} catch (error) {
  console.error('❌ FAILED TO INJECT LICENSED FONTS (CI Step Failure):', error.message)
  // CRITICAL: We exit the Node process here to fail the CI job BEFORE Chromatic runs.
  process.exit(1)
}
