<template>
  <div
    v-if="data && data.embed"
    class="BlockVideoEmbed"
  >
    <BaseImagePlaceholder
      aspect-ratio="16:9"
      dark-mode
    >
      <div v-html="data.embed.embed"></div>
    </BaseImagePlaceholder>
    <div
      v-if="data.caption || customDetailUrl"
      class="caption-area lg:px-0 p-4 print:pl-0"
    >
      <BaseImageCaption
        :data="data"
        :custom-link="customDetailUrl"
        custom-link-text="Full Video Details"
      />
    </div>
  </div>
</template>
<script lang="ts">
import type { PropType } from 'vue'
import { defineComponent } from 'vue'
import BaseImagePlaceholder from './../BaseImagePlaceholder/BaseImagePlaceholder.vue'
import BaseImageCaption from './../BaseImageCaption/BaseImageCaption.vue'

export interface BlockData {
  heading: string
  display?: boolean
  embed: {
    /** HTML for the iframe, generated by OEmbed */
    embed: string
  }
  caption: string
  credit?: string
}

export default defineComponent({
  name: 'BlockVideoEmbed',
  components: {
    BaseImagePlaceholder,
    BaseImageCaption
  },
  props: {
    /** BlockData (`embed.embed`) provides the HTML markup for the embed */
    data: {
      type: Object as PropType<BlockData>,
      required: false,
      default: undefined
    },
    /** Adds a link. Link text defaults to "Full Video Details" */
    customDetailUrl: {
      type: String,
      default: undefined
    }
  },
  mounted() {
    this.addIframeLazyLoad()
  },
  methods: {
    addIframeLazyLoad() {
      if (!this.data?.embed) {
        return
      }
      // get the iframe in this component
      const iframe = this.$el.querySelector('iframe')
      if (iframe) {
        iframe.setAttribute('loading', 'lazy')
      }
    }
  }
})
</script>

<style lang="scss">
@import '@explorer-1/common/src/scss/components/BlockVideoEmbed';
</style>
