<template>
  <div v-if="data && data.embed" class="BlockVideoEmbed">
    <BaseImagePlaceholder aspect-ratio="16:9" dark-mode>
      <div v-html="data.embed.embed"></div>
    </BaseImagePlaceholder>
    <div v-if="data.caption" class="lg:px-0 p-4">
      <BaseImageCaption :data="data" />
    </div>
  </div>
</template>
<script lang="ts">
import type { PropType } from 'vue'
import { defineComponent } from 'vue'
import BaseImagePlaceholder from './../BaseImagePlaceholder/BaseImagePlaceholder.vue'
import BaseImageCaption from './../BaseImageCaption/BaseImageCaption.vue'

interface BlockData {
  embed: {
    // HTML for the iframe, generated by OEmbed.
    embed: string
  }
  caption: string
  credit?: string
}

export default defineComponent({
  name: 'BlockVideoEmbed',
  components: {
    BaseImagePlaceholder,
    BaseImageCaption,
  },
  props: {
    data: {
      type: Object as PropType<BlockData>,
      required: false,
    },
  },
  mounted() {
    this.addIframeLazyLoad()
  },
  methods: {
    addIframeLazyLoad() {
      if (!this.data?.embed) {
        return
      }

      // TODO: not using feature detect as that would require rewriting the html output from wagtail to set data-src instead of src
      // get the iframe in this component
      const iframe = this.$el.querySelector('iframe')
      if (iframe) {
        iframe.setAttribute('loading', 'lazy')
      }
    },
  },
})
</script>

<style lang="scss">
@import '@explorer-1/common/src/scss/components/BlockVideoEmbed';
</style>
