name: Linting

# Run on the opening of a pull request and subsequent commits to it.
on: pull_request

jobs:
  lint-and-check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node ⬢
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies 🧱
        run: pnpm install

      - name: Lint scripts 🏗
        run: pnpm run lint
