# Trigger a Percy test with comment "Percy!"

name: 'Percy Visual Regression Tests'

on:
  issue_comment:
    types: [created]

jobs:
  build-and-test:
    # Run only if:
    # 1. The comment was made on a PR.
    # 2. The comment was exactly "Percy!"
    # 3. The PR is open.
    # 4. The comment was made by a member of our team.
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == 'Percy!' &&
      github.event.issue.state == 'open' &&
      contains(fromJSON('["acermak", "addisonhardy", "laespinoza", "jamesray", "Scotchester", "stephiescastle", "JMancuso79"]'), github.event.comment.user.login)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: React to PR comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: true

      - name: Get PR details
        id: pr-details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.1
          cache: npm

      - name: Install dependencies
        run: npm i --cpu x64 --os linux --include optional --ignore-scripts --package-lock false

      - name: Build Frontend Types
        run: cd apps/frontend && npx nuxi prepare

      - name: Build Storybook
        run: cd apps/storybook && npm run build:storybook

      - name: Run Percy
        id: run-percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PULL_REQUEST: ${{ github.event.issue.number }}
          PERCY_BRANCH: ${{ fromJson(steps.pr-details.outputs.data).head.ref }}
        run: |
          cd apps/storybook
          echo "PERCY_URL=$(npm run percy | grep -oP '(https:\/\/percy.io\/e5a03e0a\/smd-frontend(.*?(?=\s|$)))')" >> $GITHUB_ENV

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ env.PERCY_URL != '' && ':hedgehog: Percy Test Results: ' || '❌ Percy was unable to run.' }}
            ${{ env.PERCY_URL != '' && env.PERCY_URL || '' }}
