# Update draft release notes as Pull Requests are merged into main.
# Most configuration happens in .github/release-drafter.config.yml.
# See: https://github.com/marketplace/actions/release-drafter

name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: 'release-drafter.config.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
